	  
	  <!-- START: FULL BREAKOUT TAX TABLE LAYOUT INFORMATION -->
	  <div class="AccordionPanel">
        <div class="AccordionPanelTab">
          <h3><strong>Full Breakout tax table layout information</strong></h3>
        </div><!-- AccordionPanelTab -->
        <div class="AccordionPanelContent">          
     <p>Download the <a href="/Website/Downloads/Sample_Tables/Zip2TaxTableLayoutInformation.pdf" 
      target="_blank">CSV table layout information </a> in PDF format.</p>
      
          <p>Each table is provided in .CSV format. If you purchase the entire U.S. 
		  Tax Table, you will notice the data is ordered by ZIP code (lowest to 
		  highest). If you use Excel to examine the table, you will note that all 
		  of the data is on one tab. Note: Excel doesn't show the leading 0's in 
		  the ZIP codes. You can solve this by highlighting the ZIP code column and 
		  changing it to Zip code format.</p>

		  <p>The following is an explanation of the column headings of the U.S. Full Breakout Table:<br><br>
    
		  <strong>z2t_ID</strong> - A number generated by Zip2Tax for reference 
		  purposes. This ID remains constant from month to month except in the case 
		  of a few unincorporated areas in Washington State. If a unique identifier 
		  is needed, we suggest a combination of ZIP code and city name.<br><br>
    
		  <strong>ZIP Code</strong> - (Zone Improvement Plan) code; the U.S. system of 
		  5-digit codes that identifies the individual post office or metropolitan 
		  area delivery station associated with an address.<br><br>
    
		  <strong>Sales Tax Rate</strong> - The combined state, county and local 
		  taxes associated with an area's ZIP code.<br><br>

<strong>Rate State &ndash; </strong>The portion of the sales tax remitted to the state. <br><br>
		          
		          <strong>Reporting Code State &ndash;</strong> Some states use a reporting code, often an abbreviation of the jurisdiction, (ex: CG for &ldquo;city of Casa Grande, AZ) or sometimes a numeric code decided by the state. This field will be left blank for those states that do not require reporting codes.<br><br>
		          
		          <strong>Rate County &ndash; </strong>The portion of the sales tax remitted to the county.<br><br>
		          
		          <strong>Reporting Code County &ndash; </strong>Some counties use a reporting code. This field will be left blank for those counties that do not require reporting codes.<br><br>
		          
		          <strong>Rate City &ndash;</strong> The portion of the sales tax remitted to the city. <br><br>
		          
		          <strong>Reporting Code City &ndash;</strong> Some cities use a reporting code. This field will be left blank for those cities that do not require reporting codes.<br><br>
		          
		          <strong>Rate Special District &ndash;</strong> The portion of the sales tax remitted to a special district. This district could be a school system, a service authority -- often related to utilities or transportation -- or other municipality designated for taxation purposes such as police, fire or ambulance.<br><br>
		          
		          <strong>Reporting Code Special District &ndash; </strong>Some special districts use a reporting code. This field will be left blank for those special districts that do not require reporting codes. <br><br>
		          
		          <strong>City &ndash;</strong> An incorporated administrative district established by state charter.<br><br>
		          
		          <strong>Post Office &ndash;</strong> The name of the city used by the postal service which is not necessarily match the city named above.<br><br>
		          
		          <strong>State &ndash;</strong> A two letter abbreviation for the state.<br><br>
		          
		          <strong>County &ndash; </strong>A local level of government below the state or federal territory. Counties are used in 48 of the 50 states, while Louisiana is divided into parishes and Alaska into boroughs.<br><br>
		          
		          <strong>Shipping Taxable &ndash; </strong>&ldquo;1&rdquo; mean shipping is taxable and &ldquo;0&rdquo; means no.<br><br>
		          
		          <strong>Primary Record &ndash;</strong> Some municipalities share ZIP codes. For example: The Arizona city of New River, county of Maricopa, shares the 85087 ZIP code with the City of Phoenix. New River is the location of the post office, therefore it is the Primary Record. A &ldquo;1&rdquo; denotes the Primary Record and &ldquo;0&rdquo; means this is a shared ZIP code but the other location contains the post office.</p>
        </div><!-- AccordionPanelContent -->
      </div><!-- AccordionPanel -->
	  <!-- END: FULL BREAKOUT TAX TABLE LAYOUT INFORMATION -->	
	  
	  