
  <div id="mouseoverDiv" class="mouseoverDiv">
    <table width='100%' border="2" cellspacing="2" cellpadding="2" style="border-color:black;">
      <tr valign='top'>
        <td>

          <table width='100%' border='0' cellspacing='1' cellpadding='1'>

            <tr valign='top'>
              <td align='center'
                style="
                  font-weight: bold; 
                  font-size: 11px; 
                  font-family: Verdana, Arial, Helvetica, sans-serif;">

                  <b><span id='mouseoverTitle' style='color: red;'>Topic Goes Here</span></b>
              </td>
            </tr>

            <tr>
              <td align='center'>
                <hr>
              </td>
            </tr>

            <tr valign='top'>
              <td width='100%'
                style="
                  font-size: 10px; 
                  font-family: Verdana, Arial, Helvetica, sans-serif;">

                  <span id='mouseoverBody'>
                    This is where the mouseover text will go.
                  </span>
              </td>
            </tr>

          </table>

        </td>
      </tr>
    </table>
  </div>
