			<h3>
			<span class="glyph glyphicon glyphicon-star redFont" aria-hidden="true"></span>
			Do You Know The Facts About The States And Provinces You Do Business In?
			</h3>

		  <p><span class="firstword">States With No Sales Tax: </span><br>
		    <a href="/DE/delaware-sales-tax"
		       target="State Sales Tax Rates"
		       title="Delaware Sales Tax Rates">Delaware</a>,
		    <a href="/MT/montana-sales-tax"
		       target="State Sales Tax Rates"
		       title="Montana Sales Tax Rates">Montana</a>,
		    <a href="/NH/new-hampshire-sales-tax"
		       target="State Sales Tax Rates"
		       title="New Hampshire Sales Tax Rates">New Hampshire</a> and
		    <a href="/OR/oregon-sales-tax"
		       target="State Sales Tax Rates"
		       title="Oregon Sales Tax Rates">Oregon</a></p>

		  <p><span class="firstword">States Without Sales Tax But Some Municipalities Levy Taxes: </span><br>
		    <a href="/AK/alaska-sales-tax"
		       target="State Sales Tax Rates"
		       title="Alaska Sales Tax Rates">Alaska</a></p>

		  <p><span class="firstword">States That Levy A State-Wide Sales Tax: </span><br>
		    <a href="/CT/connecticut-sales-tax"
		       target="State Sales Tax Rates"
		       title="Connecticut Sales Tax Rates">Connecticut</a>,
         <a href="/DC/district-of-columbia-sales-tax"
		       target="State Sales Tax Rates"
		       title="District of Columbia Sales Tax Rates"> District of Columbia</a>,
		    <a href="/ID/idaho-sales-tax"
		       target="State Sales Tax Rates"
		       title="Idaho Sales Tax Rates">Idaho</a>,
		    <a href="/IN/indiana-sales-tax"
		       target="State Sales Tax Rates"
		       title="Indiana Sales Tax Rates">Indiana</a>,
		    <a href="/KY/kentucky-sales-tax"
		       target="State Sales Tax Rates"
		       title="Kentucky Sales Tax Rates">Kentucky</a>,
		    <a href="/ME/Maine-sales-tax"
		       target="State Sales Tax Rates"
		       title="Maine Sales Tax Rates">Maine</a>,
		    <a href="/MD/maryland-sales-tax"
		       target="State Sales Tax Rates"
		       title="Maryland Sales Tax Rates">Maryland</a>,
		    <a href="/MA/massachusetts-sales-tax"
		       target="State Sales Tax Rates"
		       title="Massachusetts Sales Tax Rates">Massachusetts</a>,
		    <a href="/MI/michigan-sales-tax"
		       target="State Sales Tax Rates"
		       title="Michigan Sales Tax Rates">Michigan</a>,
		    <a href="/MS/mississippi-sales-tax"
		       target="State Sales Tax Rates"
		       title="Mississippi Sales Tax Rates">Mississippi</a>,
		    <a href="/NJ/new-jersey-sales-tax"
		       target="State Sales Tax Rates"
		       title="New Jersey Sales Tax Rates">New Jersey</a>,
		    <a href="/RI/rhode-island-sales-tax"
		       target="State Sales Tax Rates"
		       title="Rhode Island Sales Tax Rates">Rhode Island</a>,
		    <a href="/VA/virginia-sales-tax"
		       target="State Sales Tax Rates"
		       title="Virginia Sales Tax Rates">Virginia</a>, and
		    <a href="/WV/west-virginia-sales-tax"
		       target="State Sales Tax Rates"
		       title="West Virginia Sales Tax Rates">West Virginia</a></p>

		  <p><span class="firstword">States That Levy A State-Wide Sales Tax As Well As County Taxes: </span><br>
		    <a href="/FL/florida-sales-tax"
		       target="State Sales Tax Rates"
		       title="Florida Sales Tax Rates">Florida</a>,
		    <a href="/NV/nevada-sales-tax"
		       target="State Sales Tax Rates"
		       title="Nevada Sales Tax Rates">Nevada</a>,
		    <a href="/NC/north-carolina-sales-tax"
		       target="State Sales Tax Rates"
		       title="North Carolina Sales Tax Rates">North Carolina</a>,
		    <a href="/OH/ohio-sales-tax"
		       target="State Sales Tax Rates"
		       title="Ohio Sales Tax Rates">Ohio</a>,
		    <a href="/WI/wisconsin-sales-tax"
		       target="State Sales Tax Rates"
		       title="Wisconsin Sales Tax Rates">Wisconsin</a> and
		    <a href="/WY/wyoming-sales-tax"
		       target="State Sales Tax Rates"
		       title="Wyoming Sales Tax Rates">Wyoming</a></p>

		  <p><span class="firstword">States With A State-Wide Sales Tax As Well As County And Municipal Taxes: </span><br>
		    <a href="/AL/alabama-sales-tax"
		       target="State Sales Tax Rates"
		       title="Alabama Sales Tax Rates">Alabama</a>,
		    <a href="/AZ/arizona-sales-tax"
		       target="State Sales Tax Rates"
		       title="Arizona Sales Tax Rates">Arizona</a>,
		    <a href="/AR/arkansas-sales-tax"
		       target="State Sales Tax Rates"
		       title="Arkansas Sales Tax Rates">Arkansas</a>,
		    <a href="/CA/california-sales-tax"
		       target="State Sales Tax Rates"
		       title="California Sales Tax Rates">California</a>,
		    <a href="/GA/georgia-sales-tax"
		       target="State Sales Tax Rates"
		       title="Georgia Sales Tax Rates">Georgia</a>,
		    <a href="/HI/hawaii-sales-tax"
		       target="State Sales Tax Rates"
		       title="Hawaii Sales Tax Rates"><span class="ref-HI">Hawaii</span><span class="footnote-HI">*</span></a>,
		    <a href="/IL/illinois-sales-tax"
		       target="State Sales Tax Rates"
		       title="Illinois Sales Tax Rates">Illinois</a>,
		    <a href="/IA/iowa-sales-tax"
		       target="State Sales Tax Rates"
		       title="Iowa Sales Tax Rates">Iowa</a>,
		    <a href="/KS/Kansas-sales-tax"
		       target="State Sales Tax Rates"
		       title="Kansas Sales Tax Rates">Kansas</a>,
		    <a href="/LA/louisiana-sales-tax"
		       target="State Sales Tax Rates"
		       title="Louisiana Sales Tax Rates">Louisiana</a>,
		    <a href="/MN/minnesota-sales-tax"
		       target="State Sales Tax Rates"
		       title="Minnesota Sales Tax Rates">Minnesota</a>,
		    <a href="/MO/missouri-sales-tax"
		       target="State Sales Tax Rates"
		       title="Missouri Sales Tax Rates">Missouri</a>,
		    <a href="/NE/nebraska-sales-tax"
		       target="State Sales Tax Rates"
		       title="Nebraska Sales Tax Rates">Nebraska</a>,
		    <a href="/NM/new-mexico-sales-tax"
		       target="State Sales Tax Rates"
		       title="New Mexico Sales Tax Rates">New Mexico</a>,
		    <a href="/NY/new-york-sales-tax"
		       target="State Sales Tax Rates"
		       title="New York Sales Tax Rates">New York</a>,
		    <a href="/ND/north-dakota-sales-tax"
		       target="State Sales Tax Rates"
		       title="North Dakota Sales Tax Rates">North Dakota</a>,
		    <a href="/OK/oklahoma-sales-tax"
		       target="State Sales Tax Rates"
		       title="Oklahoma Sales Tax Rates">Oklahoma</a>,
		    <a href="/PA/pennsylvania-sales-tax"
		       target="State Sales Tax Rates"
		       title="Pennsylvania Sales Tax Rates">Pennsylvania</a>,
		    <a href="/SC/south-carolina-sales-tax"
		       target="State Sales Tax Rates"
		       title="South Carolina Sales Tax Rates">South Carolina</a>,
		    <a href="/SD/south-dakota-sales-tax"
		       target="State Sales Tax Rates"
		       title="South Dakota Sales Tax Rates">South Dakota</a>,
		    <a href="/TN/tennessee-sales-tax"
		       target="State Sales Tax Rates"
		       title="Tennessee Sales Tax Rates">Tennessee</a>,
		    <a href="/TX/texas-sales-tax"
		       target="State Sales Tax Rates"
		       title="Texas Sales Tax Rates">Texas</a>,
		    <a href="/UT/utah-sales-tax"
		       target="State Sales Tax Rates"
		       title="Utah Sales Tax Rates">Utah</a> and
		    <a href="/VT/vermont-sales-tax"
		       target="State Sales Tax Rates"
		       title="Vermont Sales Tax Rates">Vermont</a>, and 
         <a href="/WA/washington-sales-tax"
		       target="State Sales Tax Rates"
		       title="Washington Sales Tax Rates"> Washington</a> </p>

		  <p><span class="firstword">States With No Use Tax: </span><br>
		    <a href="/MT/montana-sales-tax"
		       target="State Use Tax Rates"
		       title="Montana Use Tax Rates">Montana</a>,
		    <a href="/NH/new-hampshire-sales-tax"
		       target="State Use Tax Rates"
		       title="New Hampshire Use Tax Rates">New Hampshire</a> and
		    <a href="/OR/oregon-sales-tax"
		       target="State Use Tax Rates"
		       title="Oregon Use Tax Rates">Oregon</a></p>

		  <p><span class="firstword">States With A Use Tax That Is Not The Same As The Sales Tax: </span><br>
		    <a href="/AL/alabama-sales-tax"
		       target="State Use Tax Rates"
		       title="Alabama Use Tax Rates">Alabama</a>,
		    <a href="/AZ/arizona-sales-tax"
		       target="State Use Tax Rates"
		       title="Arizona Use Tax Rates">Arizona</a>,
		    <a href="/CO/colorado-sales-tax"
		       target="State Use Tax Rates"
		       title="Colorado Use Tax Rates">Colorado</a>,
		    <a href="/MO/missouri-sales-tax"
		       target="State Use Tax Rates"
		       title="Missouri Use Tax Rates">Missouri</a> and
		    <a href="/OK/oklahoma-sales-tax"
		       target="State Use Tax Rates"
		       title="Oklahoma Use Tax Rates">Oklahoma</a></p>

		  <p><span class="firstword">States With A State-Wide Use Tax, But No Local Use Taxes: </span><br>
		    <a href="/IL/illinois-sales-tax"
		       target="State Use Tax Rates"
		       title="Illinois Use Tax Rates">Illinois</a>,
		    <a href="/IA/iowa-sales-tax"
		       target="State Use Tax Rates"
		       title="Iowa Use Tax Rates">Iowa</a>,
		    <a href="/NM/new-mexico-sales-tax"
		       target="State Use Tax Rates"
		       title="New Mexico Use Tax Rates">New Mexico</a>,
		    <a href="/VT/vermont-sales-tax"
		       target="State Use Tax Rates"
		       title="Vermont Use Tax Rates">Vermont</a> and
		    <a href="/WI/wisconsin-sales-tax"
		       target="State Use Tax Rates"
		       title="Wisconsin Use Tax Rates">Wisconsin</a></p>


                  <p><span class="firstword">Provinces And Territories Participating With The Harmonized Sales Tax</span><br>
		    British Columbia, 
		    New Brunswick, 
		    Newfoundland and Labrador, 
		    Nova Scotia And
		    Ontario</p>

                  <p><span class="firstword">Provinces And Territories Using An Individual Retail Sales Tax</span><br> 
		    Manitoba, 
		    Prince Edward Island, 
		    Saskatchewan And 
		    <span class="ref-QC">Quebec</span><span class="footnote-QC">**</span>
        
                  <p><span class="firstword">Provinces And Territories Requiring Only The Goods and Services Tax (GST)</span><br> 
		    Alberta, 
		    Northwest Territories, 
		    Nunavut And
		    Yukon</p>

               <p>*Technically, Hawaii has an excise tax, not a sales tax<br>
                  **Quebec administers both the federal GST and its own Quebec Sales Tax (QST)</p>
	    
