<ul id="flexmenu1" class="flexdropdownmenu">
  <!-- Home -->
  <li><a href="#">Item Folder 1a</a>
    <ul>
      <li><a href="#">Sub Item 1.1a</a></li>
      <li><a href="#">Sub Item 1.2a</a></li>
      <li><a href="#">Sub Item 1.3a</a></li>
      <li><a href="#">Sub Item 1.4a</a></li>
      <li><a href="#">Sub Item 1.5a</a></li>
    </ul>
  </li>

  <!-- Accounts -->
  <li><a href="#">Item Folder 2a</a>
    <ul>
      <li><a href="#">Sub Item 2.1a</a></li>
      <li><a href="#">Sub Item 2.2a</a></li>
      <li><a href="#">Sub Item 2.3a</a></li>
    </ul>
  </li>

  <!-- Orders -->
  <li><a href="#">Item Folder 3a</a>
    <ul>
      <li><a href="#">Sub Item 3.1a</a></li>
      <li><a href="#">Sub Item 3.2a</a></li>
      <li><a href="#">Sub Item 3.3a</a></li>
      <li><a href="#">Sub Item 3.4a</a></li>
      <li><a href="#">Sub Item 3.5a</a></li>
      <li><a href="#">Sub Item 3.6a</a></li>
    </ul>
  </li>

  <li><a href="#">Item 4a</a></li>

  <!-- Sales -->
  <li><a href="#">Item Folder 5a</a>
    <ul>
      <li><a href="#">Sub Item 5.1a</a></li>
      <li><a href="#">Sub Item 5.2a</a></li>
      <li><a href="#">Sub Item 5.3a</a></li>
      <li><a href="#">Sub Item 5.4a</a></li>
    </ul>
  </li>
  
  <!-- Maintenance -->
  <li><a href="#">Item Folder 6a</a>
    <ul>
      <li><a href="#">Sub Item 6.1a</a></li>
      <li><a href="#">Sub Item 6.2a</a></li>
    </ul>
  </li>
</ul>

<!-- Home -->
<ul id="Home" class="flexdropdownmenu">
  <li><a href="https://www.harvestamerican.info/menu/index.asp">Employee menu</a></li>
  <li><a href="https://www.harvestamerican.info/ha_Backoffice/ha_home.asp">Harvest Backofice</a></li>
  <li><a href="https://www.zip2tax.info/z2t_Backoffice/index.asp">Zip2tax Backoffice</a></li>
  <li><a href="http://www.zip2tax.com/Backoffice/z2t_BackofficeSummary.asp">Old Zip2tax Backoffice</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boAccounts.asp">Number-it Backoffice</a></li>
</ul>

<!-- Accounts -->
<ul id="Accounts" class="flexdropdownmenu">
  <li><a href="http://www.number-it.com/Home/BackOffice/boAccounts.asp">Accounts</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boProspects.asp?startdate=1/1/1900&enddate=12/31/2050&user=All">Prospects</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boToDo.asp">To-Do List</a></li>
</ul>

<!-- Orders -->
<ul id="Orders" class="flexdropdownmenu">
  <li><a href="http://www.number-it.com/Home/BackOffice/boOrders.asp?oRange=Today">Today's Orders</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boOrders.asp?oRange=Yesterday">Yesterday's Orders</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boOrders.asp?oRange=Mock">Mock Orders</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boOrders.asp?oRange=Pending">Pending Orders</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boOrders.asp?oRange=Unpaid">Unpaid Orders</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boWholesaleOrder.asp">Place a Wholesale Order</a></li>
</ul>

<!-- Sales -->
<ul id="Sales" class="flexdropdownmenu">
  <li><a href="http://www.number-it.com/Home/BackOffice/boSales/boDailyActivity.asp">Daily Sales</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boSales/boMonthlyActivity.asp">Monthly Sales</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boSales/boSalesBreakout.asp">Sales Breakout</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boSales/boSalesBreakoutGL.asp">GL Breakout Harvest</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boSales/boSalesBreakoutGLZip2Tax.asp">GL Breakout Zip2Tax</a></li>
</ul>

<!-- Maintenance -->
<ul id="Maintenance" class="flexdropdownmenu">
  <li><a href="http://www.number-it.com/Home/BackOffice/boMaintenance/boStateLinks.asp">State Links</a></li>
  <li><a href="http://www.number-it.com/Home/BackOffice/boMaintenance/boConstantContact.asp">Constant Contact</a></li>
</ul>
